# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: AWS-CLI
    before:
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
